server:
  port: 9090
  servlet:
    context-path: /demo

spring:
  #数据源配置
  datasource:
    #开发环境
    url: jdbc:mysql://localhost:3306/pagehelper?useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis扫描路径
mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*.xml

#通用mapper
mapper:
  mappers:
    - com.example.demo.base.BaseMapper
  not-empty: false
  identity: MYSQL